site_name: 'HPE Storage Container Orchestrator Documentation'
site_description: 'Reference documentation for container orchestrator integration for HPE storage'
site_url: 'https://scod.hpedev.io/'
site_author: 'Hewlett Packard Enterprise'
theme: 
  name: readthedocs
  custom_dir: hpe_theme/
repo_name: 'hpe-storage/scod'
repo_url: 'https://github.com/hpe-storage/scod'
copyright: 'Copyright 2020 Hewlett Packard Enterprise Development LP'
extra_css:
  - css/hpedev.css
google_analytics:
  - 'UA-79554149-3'
  - 'auto'
use_directory_urls: false
edit_uri: ''
markdown_extensions:
  - admonition:
  - toc:
      permalink: True
      separator: "_"
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
plugins:
  - search:
  - redirects:
      redirect_maps:
        'docker_volume_plugins/hpe_cloud_volumes.md': 'docker_volume_plugins/hpe_cloud_volumes/index.md'
        'docker_volume_plugins/hpe_nimble_storage.md': 'docker_volume_plugins/hpe_nimble_storage/index.md'
        'container_storage_provider/hpe_nimble_storage/index.md': 'container_storage_provider/hpe_alletra_6000/index.md'
        'container_storage_provider/hpe_3par_primera/index.md': 'container_storage_provider/hpe_alletra_9000/index.md'
        'partners/rancher_labs/index.md': 'partners/suse_rancher/index.md'
nav:
  - WELCOME:
    - 'Get started!': 'welcome/index.md'
  - HPE CSI DRIVER FOR KUBERNETES:
    - 'Overview': 'csi_driver/index.md'
    - 'Deployment': 'csi_driver/deployment.md'
    - 'Using': 'csi_driver/using.md'
    - 'Pod Monitor': 'csi_driver/monitor.md'
    - 'Diagnostics': 'csi_driver/diagnostics.md'
    - 'Metrics': 'csi_driver/metrics.md'
  - CONTAINER STORAGE PROVIDERS:
    - 'HPE Alletra 6000 and Nimble': 'container_storage_provider/hpe_alletra_6000/index.md'
    - 'HPE Alletra 9000 and Primera/3PAR': 'container_storage_provider/hpe_alletra_9000/index.md'
# - WORKLOAD BLUEPRINTS:
#   - 'Running MongoDB on HPE Storage': 'workloads/mongodb/index.md'
#   - 'Hybrid Cloud CI/CD pipelines': 'workloads/mongodb/hybrid_cloud_cicd.md'
# - REFERENCE ARCHITECTURES:
#   - 'HPE RA Library': ''
#   - 'HPE InfoSight': ''
#   - 'External': ''
  - HPE EZMERAL CONTAINER PLATFORM:
    - 'Install HPE CSI Driver': "ezmeral_container_platform/install.md"
  - PARTNER ECOSYSTEMS:
    - 'Commvault': "partners/commvault/index.md"
    - 'Kasten by Veeam': 'partners/kasten/index.md'
    - 'Mirantis': 'partners/mirantis/index.md'
    - 'Red Hat OpenShift': 'partners/redhat_openshift/index.md'
    - 'SUSE Rancher': 'partners/suse_rancher/index.md'
    - 'VMware': 'partners/vmware/index.md'
#   - 'Google Anthos': 'partners/google_cloud_anthos/index.md'
  - LEARN:
    - 'Cloud-Native, Containers & DevOps': 'learn/containers101/index.md'
    - 'Persistent Storage for Kubernetes': 'learn/persistent_storage/index.md'
    - 'For HPE partners:<br />&nbsp;&nbsp; Introduction to Containers': 'learn/introduction_to_containers/index.md'
    - 'Introduction to CSI Primitives': 'learn/csi_primitives/index.md'
    - 'Video Gallery': 'learn/video_gallery/index.md'
    - 'Interactive CSI Workshop': 'learn/csi_workshop/index.md'
  - COMMUNITY:
    - 'HPE Developer Community': 'https://developer.hpe.com'
    - 'Sign up to HPE DEV on Slack': 'https://slack.hpedev.io'
    - 'Got feedback?': 'https://github.com/hpe-storage/scod/issues/new?title=I have some feedback on SCOD'
  - EXTERNAL LINKS:
    - 'SCOD on GitHub': 'https://github.com/hpe-storage/scod'
    - 'HPE Storage on GitHub': 'https://github.com/hpe-storage'
    - 'Storage for Containers on hpe.com': 'https://hpe.com/storage/containers'
  - LEGAL:
    - 'Contributing': 'legal/contributing/index.md'
    - 'Support': 'legal/support/index.md'
    - 'License': 'legal/license/index.md'
    - 'Notices': 'legal/notices/index.md'
  - LEGACY DRIVERS AND PLUGINS:
    - 'Docker, FlexVolume and CSPs': 'legacy/index.md'
