site_name: 'HPE Storage Container Orchestrator Documentation'
site_description: 'Reference documentation for container orchestrator integration for HPE storage'
site_url: 'https://scod.hpedev.io/'
site_author: 'Hewlett Packard Enterprise'
theme: 
  name: readthedocs
  custom_dir: hpe_theme/
repo_name: 'hpe-storage/scod'
repo_url: 'https://github.com/hpe-storage/scod'
copyright: 'Copyright 2020 Hewlett Packard Enterprise Development LP'
extra_css:
  - css/hpedev.css
google_analytics:
  - 'UA-79554149-3'
  - 'auto'
use_directory_urls: false
edit_uri: ''
markdown_extensions:
  - admonition:
  - toc:
      permalink: True
      separator: "_"
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
plugins:
  - search:
  - redirects:
      redirect_maps:
        'docker_volume_plugins/hpe_cloud_volumes.md': 'docker_volume_plugins/hpe_cloud_volumes/index.md'
        'docker_volume_plugins/hpe_nimble_storage.md': 'docker_volume_plugins/hpe_nimble_storage/index.md'
nav:
  - WELCOME:
    - 'Get started!': 'welcome/index.md'
  - HPE CSI DRIVER FOR KUBERNETES:
    - 'Overview': 'csi_driver/index.md'
    - 'Deployment': 'csi_driver/deployment.md'
    - 'Using': 'csi_driver/using.md'
    - 'Node Monitor': 'csi_driver/monitor.md'
    - 'Diagnostics': 'csi_driver/diagnostics.md'
  - CONTAINER STORAGE PROVIDERS:
    - 'HPE 3PAR and Primera': 'container_storage_provider/hpe_3par_primera/index.md'
#   - 'HPE Cloud Volumes': 'csp/cloud_volumes/index.md'
    - 'HPE Nimble Storage': 'container_storage_provider/hpe_nimble_storage/index.md'
# - HPE CONTAINER PLATFORM:
#   - 'Overview': 'hcp/overview.md'
#   - 'Configure': 'hcp/configure.md'
# - MANAGED KUBERNETES:
#   - 'Amazon Elastic Kubernetes Engine': 'managed/amazon_elastic_kubernetes_service/index.md'
#   - 'Azure Kubernetes Service': 'managed/azure_kubernetes_service/index.md'
#   - 'Google Kubernetes Engine': 'managed/google_kubernetes_engine/index.md'
  - LEGACY FLEXVOLUME DRIVER:
    - 'Container Provider: Nimble and CV': 'flexvolume_driver/container_provider/index.md'
    - 'Ansible installer for 3PAR/Primera': 'flexvolume_driver/hpe_3par_primera_installer/index.md'
    - 'History: Dory and Doryd ': 'flexvolume_driver/dory/index.md'
  - DOCKER VOLUME PLUGINS:
#    - 'HPE 3PAR and Primera': 'docker_volume_plugins/hpe_3par_primera/index.md'
    - 'HPE Cloud Volumes': 'docker_volume_plugins/hpe_cloud_volumes/index.md'
    - 'HPE Nimble Storage': 'docker_volume_plugins/hpe_nimble_storage/index.md'
# - WORKLOAD BLUEPRINTS:
#   - 'Running MongoDB on HPE Storage': 'workloads/mongodb/index.md'
#   - 'Hybrid Cloud CI/CD pipelines': 'workloads/mongodb/hybrid_cloud_cicd.md'
# - REFERENCE ARCHITECTURES:
#   - 'HPE RA Library': ''
#   - 'HPE InfoSight': ''
#   - 'External': ''
  - PARTNER ECOSYSTEMS:
    - 'Red Hat OpenShift': 'partners/redhat_openshift/index.md'
#   - 'Google Anthos': 'partners/google_cloud_anthos/index.md'
#   - 'Rancher Labs': 'partners/rancher_labs/index.md'
  - LEARN:
    - 'Cloud-Native, Containers & DevOps': 'learn/containers101/index.md'
    - 'Persistent Storage for Kubernetes': 'learn/persistent_storage/index.md'
#   - 'Using Docker Volume plugins': 'learn/docker_volume_plugins.md'
#   - 'External Resources': 'learn/links.md'
  - COMMUNITY:
    - 'HPE Developer Community': 'https://developer.hpe.com'
    - 'Sign up to HPE DEV on Slack': 'https://slack.hpedev.io'
    - 'Got feedback?': 'https://github.com/hpe-storage/scod/issues/new?title=I have some feedback on SCOD'
#   - 'Blogs': 'community/blogs/index.md'
  - EXTERNAL LINKS:
    - 'SCOD on GitHub': 'https://github.com/hpe-storage/scod'
    - 'HPE Storage on GitHub': 'https://github.com/hpe-storage'
    - 'Storage for Containers on hpe.com': 'https://hpe.com/storage/containers'
  - LEGAL:
    - 'Contributing': 'legal/contributing/index.md'
    - 'Support': 'legal/support/index.md'
    - 'License': 'legal/license/index.md'
